lazyPaladinLoad.metadata:updateRevisionFromKeyword("$Revision: 715 $")

function lazyPaladinLoad.LoadPaladinLocalization(locale)

	lazyPaladinLocale.enUS.ACTION_TTS.concAura      = "Concentration Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.devAura       = "Devotion Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.fireAura      = "Fire Resistance Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.frostAura     = "Frost Resistance Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.retAura       = "Retribution Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.sanctAura     = "Sanctity Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.shadowAura    = "Shadow Resistance Aura"
	lazyPaladinLocale.enUS.ACTION_TTS.blessKings    = "Blessing of Kings"
	lazyPaladinLocale.enUS.ACTION_TTS.blessLight    = "Blessing of Light"
	lazyPaladinLocale.enUS.ACTION_TTS.blessMight    = "Blessing of Might"
	lazyPaladinLocale.enUS.ACTION_TTS.blessSlv      = "Blessing of Salvation"
	lazyPaladinLocale.enUS.ACTION_TTS.blessSnct     = "Blessing of Sanctuary"
	lazyPaladinLocale.enUS.ACTION_TTS.blessWisdom   = "Blessing of Wisdom"
	lazyPaladinLocale.enUS.ACTION_TTS.cleanse       = "Cleanse"
	lazyPaladinLocale.enUS.ACTION_TTS.consecrate    = "Consecration"
	lazyPaladinLocale.enUS.ACTION_TTS.crusaderStrike= "Crusader Strike"
	lazyPaladinLocale.enUS.ACTION_TTS.divFavor      = "Divine Favor"
	lazyPaladinLocale.enUS.ACTION_TTS.divIntr       = "Divine Intervention"
	lazyPaladinLocale.enUS.ACTION_TTS.divProt       = "Divine Protection"
	lazyPaladinLocale.enUS.ACTION_TTS.divShield     = "Divine Shield"
	lazyPaladinLocale.enUS.ACTION_TTS.exorcism      = "Exorcism"
	lazyPaladinLocale.enUS.ACTION_TTS.flashLight    = "Flash of Light"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessKings   = "Greater Blessing of Kings"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessLight   = "Greater Blessing of Light"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessMight   = "Greater Blessing of Might"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessSlv     = "Greater Blessing of Salvation"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessSnct    = "Greater Blessing of Sanctuary"
	lazyPaladinLocale.enUS.ACTION_TTS.gBlessWisdom  = "Greater Blessing of Wisdom"
	lazyPaladinLocale.enUS.ACTION_TTS.hmrJustice    = "Hammer of Justice"
	lazyPaladinLocale.enUS.ACTION_TTS.hmrWrath      = "Hammer of Wrath"
	lazyPaladinLocale.enUS.ACTION_TTS.holyLight     = "Holy Light"
	lazyPaladinLocale.enUS.ACTION_TTS.holyShield    = "Holy Shield"
	lazyPaladinLocale.enUS.ACTION_TTS.holyShock     = "Holy Shock"
	lazyPaladinLocale.enUS.ACTION_TTS.holyStrike    = "Holy Strike"
	lazyPaladinLocale.enUS.ACTION_TTS.holyWrath     = "Holy Wrath"
	lazyPaladinLocale.enUS.ACTION_TTS.hof           = "Hand of Freedom"
	lazyPaladinLocale.enUS.ACTION_TTS.hop           = "Hand of Protection"
	lazyPaladinLocale.enUS.ACTION_TTS.hor           = "Hand of Reckoning"
	lazyPaladinLocale.enUS.ACTION_TTS.hos           = "Hand of Sacrifice"
	lazyPaladinLocale.enUS.ACTION_TTS.judge         = "Judgement"
	lazyPaladinLocale.enUS.ACTION_TTS.layOnHands    = "Lay on Hands"
	lazyPaladinLocale.enUS.ACTION_TTS.purify        = "Purify"
	lazyPaladinLocale.enUS.ACTION_TTS.redemption    = "Redemption"
	lazyPaladinLocale.enUS.ACTION_TTS.repentance    = "Repentance"
	lazyPaladinLocale.enUS.ACTION_TTS.rightFury     = "Righteous Fury"
	lazyPaladinLocale.enUS.ACTION_TTS.sealCommand   = "Seal of Command"
	lazyPaladinLocale.enUS.ACTION_TTS.sealCrusader  = "Seal of the Crusader"
	lazyPaladinLocale.enUS.ACTION_TTS.sealJustice   = "Seal of Justice"
	lazyPaladinLocale.enUS.ACTION_TTS.sealLight     = "Seal of Light"
	lazyPaladinLocale.enUS.ACTION_TTS.sealRight     = "Seal of Righteousness"
	lazyPaladinLocale.enUS.ACTION_TTS.sealWisdom    = "Seal of Wisdom"
	lazyPaladinLocale.enUS.ACTION_TTS.senseUndead   = "Sense Undead"
	lazyPaladinLocale.enUS.ACTION_TTS.smnCharger	= "Summon Charger"
	lazyPaladinLocale.enUS.ACTION_TTS.smnWarhorse   = "Summon Warhorse"
	lazyPaladinLocale.enUS.ACTION_TTS.turnUndead    = "Turn Undead"
	lazyPaladinLocale.enUS.ACTION_TTS.zybl          = "Bulwark of the Righteous"
	lazyPaladinLocale.enUS.ACTION_TTS.ch            = "Daybreak"

	-- LazyPaladin.lua
	PALADIN_ADDON_LOADED = " loaded. Powered by "

	-- ParsePaladin.lua
	function lazyPaladin.CustomLocaleHelp() return [[<H2>Paladin Criteria:</H2>]] end

	if (locale == "zhCN") then

		lazyPaladinLocale.zhCN.ACTION_TTS.concAura      = "专注光环"
		lazyPaladinLocale.zhCN.ACTION_TTS.devAura       = "虔诚光环"
		lazyPaladinLocale.zhCN.ACTION_TTS.fireAura      = "火焰抗性光环"
		lazyPaladinLocale.zhCN.ACTION_TTS.frostAura     = "冰霜抗性光环"
		lazyPaladinLocale.zhCN.ACTION_TTS.retAura       = "惩罚光环"
		lazyPaladinLocale.zhCN.ACTION_TTS.sanctAura     = "圣洁光环"
		lazyPaladinLocale.zhCN.ACTION_TTS.shadowAura    = "暗影抗性光环"
		lazyPaladinLocale.zhCN.ACTION_TTS.blessKings    = "王者祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.blessLight    = "光明祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.blessMight    = "力量祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.blessSlv      = "拯救祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.blessSnct     = "庇护祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.blessWisdom   = "智慧祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.cleanse       = "清洁术"
		lazyPaladinLocale.zhCN.ACTION_TTS.consecrate    = "奉献"
		lazyPaladinLocale.zhCN.ACTION_TTS.crusaderStrike= "十字军打击"
		lazyPaladinLocale.zhCN.ACTION_TTS.divFavor      = "神恩术"
		lazyPaladinLocale.zhCN.ACTION_TTS.divIntr       = "神圣干涉"
		lazyPaladinLocale.zhCN.ACTION_TTS.divProt       = "圣佑术"
		lazyPaladinLocale.zhCN.ACTION_TTS.divShield     = "圣盾术"
		lazyPaladinLocale.zhCN.ACTION_TTS.exorcism      = "驱邪术"
		lazyPaladinLocale.zhCN.ACTION_TTS.flashLight    = "圣光闪现"
		lazyPaladinLocale.zhCN.ACTION_TTS.gBlessKings   = "强效王者祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.gBlessLight   = "强效光明祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.gBlessMight   = "强效力量祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.gBlessSlv     = "强效拯救祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.gBlessSnct    = "强效庇护祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.gBlessWisdom  = "强效智慧祝福"
		lazyPaladinLocale.zhCN.ACTION_TTS.hmrJustice    = "制裁之锤"
		lazyPaladinLocale.zhCN.ACTION_TTS.hmrWrath      = "愤怒之锤"
		lazyPaladinLocale.zhCN.ACTION_TTS.holyLight     = "圣光术"
		lazyPaladinLocale.zhCN.ACTION_TTS.holyShield    = "神圣之盾"
		lazyPaladinLocale.zhCN.ACTION_TTS.holyShock     = "神圣震击"
		lazyPaladinLocale.zhCN.ACTION_TTS.holyStrike    = "神圣打击"
		lazyPaladinLocale.zhCN.ACTION_TTS.holyWrath     = "神圣愤怒"
		lazyPaladinLocale.zhCN.ACTION_TTS.hof           = "自由之手"
		lazyPaladinLocale.zhCN.ACTION_TTS.hop           = "保护之手"
		lazyPaladinLocale.zhCN.ACTION_TTS.hor           = "清算之手"
		lazyPaladinLocale.zhCN.ACTION_TTS.hos           = "牺牲之手"
		lazyPaladinLocale.zhCN.ACTION_TTS.judge         = "审判"
		lazyPaladinLocale.zhCN.ACTION_TTS.layOnHands    = "圣疗术"
		lazyPaladinLocale.zhCN.ACTION_TTS.purify        = "纯净术"
		lazyPaladinLocale.zhCN.ACTION_TTS.redemption    = "救赎"
		lazyPaladinLocale.zhCN.ACTION_TTS.repentance    = "忏悔"
		lazyPaladinLocale.zhCN.ACTION_TTS.rightFury     = "正义之怒"
		lazyPaladinLocale.zhCN.ACTION_TTS.sealCommand   = "命令圣印"
		lazyPaladinLocale.zhCN.ACTION_TTS.sealCrusader  = "十字军圣印"
		lazyPaladinLocale.zhCN.ACTION_TTS.sealJustice   = "公正圣印"
		lazyPaladinLocale.zhCN.ACTION_TTS.sealLight     = "光明圣印"
		lazyPaladinLocale.zhCN.ACTION_TTS.sealRight     = "正义圣印"
		lazyPaladinLocale.zhCN.ACTION_TTS.sealWisdom    = "智慧圣印"
		lazyPaladinLocale.zhCN.ACTION_TTS.senseUndead   = "感知亡灵"
		lazyPaladinLocale.zhCN.ACTION_TTS.smnCharger	= "召唤战马"
		lazyPaladinLocale.zhCN.ACTION_TTS.smnWarhorse   = "召唤军马"
		lazyPaladinLocale.zhCN.ACTION_TTS.turnUndead    = "超度亡灵"
		lazyPaladinLocale.zhCN.ACTION_TTS.zybl          = "正义壁垒"
		lazyPaladinLocale.zhCN.ACTION_TTS.ch            = "晨辉"

	end
end
